language: php

php:
  - '7.1'

before_install:
  - composer config http-basic.packagist.lkwdwrd.com $SATIS_USER $SATIS_PASS
# Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - composer install
  - yarn install
  - yarn run pack

script: composer testAll

cache:
  yarn: true
  directories:
    - vendor
    - node_modules

branches:
  only:
    - master

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9da0e217f314_key -iv $encrypted_9da0e217f314_iv
  -in .deploy/deployer.enc -out /tmp/deployer -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deployer
  - ssh-add /tmp/deployer
  - rm /tmp/deployer

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/.deploy/deploy.sh $PROD_USER $PROD_IP $PROD_PATH
  skip_cleanup: true
  on:
    branch: master

addons:
  ssh_known_hosts: 104.131.95.230

notifications:
  slack:
    secure: RKiLke8IpbEcV3jxse/5Pv9MZb/nZuxNTl2BSvrBNjEStsCmiJxjO/UnyY3nqTvU1RQjQn6/eMU3xcN6XhCYPJi+/Y74OoW3g1ohmD/3dA5n7lVwFJgqXL/f6alamcuhr93Meg3KT4d9A227NaKRMuOnPYlTOrIyA0RHopIhuCbQZ73kxAqySsfN6I4HFxRt6LXRJxBDBkQGO7K11EOQF0GR80WPzpVBn5BEn/6pgJMovGC04mWvFGeobHsjpIfcEw6sdL9DMww4RxzykWMxlPeuUigt9MhmDtdmiXFCLZS5jcY5nBLtZmzGF9ghJQKfBMpPbpk8uLZ6fLGfGVhj3m/op2tH87Ss9l6pjb5RQY635ZLkpE3jUGjLhvw5yhZ0/Xbhcl7BYorm879IWFALsOW7h4y/5oVmW1ke/i/RREYSfsdr9lFCX1uCDrg9McdSoI+J2cycSoSlb9lukVVxDxvtzzWhw/zzdSED/vG+Wr5Z7U4hWrnDiegBymDF79ZyF6pzlnSN97ciGgftee3zB4hjMTULX6eaJZyYUXzj+zeJimrwlwyOi52GmyKEHc9A9AR6MUxMZjgJpkWYsm2JJ9jECeurOvFQ1Gku9AL51heyLmOUGbYk0BX31Skyg4D2m4nJ1n7n/z4ieulryEt7Q+H44Wy3YDkjhKFQZVM3SLc=
