language: php
php:
    - '5.6'
install: composer install && npm install
script: composer testAll
cache:
  directories:
    - vendor
    - node_modules
branches:
    only:
        - master
before_deploy:
    - openssl aes-256-cbc -K $encrypted_9da0e217f314_key -iv $encrypted_9da0e217f314_iv -in deployer.enc -out /tmp/deployer -d
    - eval "($ssh-agent -s)"
    - chmod 600 /tmp/deployer
    - ssh-add /tmp/deployer
    - rm /tmp/deployer
deploy:
    provider: script
    script: .deploy/deploy.sh $PROD_USER $PROD_IP $PROD_PATH
    skip_cleanup: true
    on:
        branch: master
addons:
    ssh_known_hosts: 104.131.95.230
